#!/usr/bin/env sh

# MIT License
# 
# Copyright (c) 2026 Yaofei Zheng
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

if [ 4 -ne $# ];
then
    echo "params error"
    echo "we need {new temp branch} {target branch} {target commit} {timestamp}"
    echo "example: git-change-commit-time temp-new main 3ca5a9fcb77933d3b9bc0c1babcd44a5eade2361 \"2026-07-28T21:46:10+08:00\""
else
    echo $0
    echo $1 # new temp branch
    echo $2 # target branch
    echo $3 # target commit
    echo $4 # timestamp 2022-01-01T00:00:00+08:00

    echo "git-change-commit-time create new temp branch"
    git checkout -b "$1" "$3"

    echo "git-change-commit-time change target commit date"
    git commit --amend --date="$4" --reset-author --no-edit

    echo "git-change-commit-time checkout target branch"
    git checkout "$2"

    echo "git-change-commit-time rebase target branch"
    git rebase --committer-date-is-author-date --onto="$1" "$3"

    echo "git-change-commit-time delete new temp branch"
    git branch -d "$1"
fi
